spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?user=postgres.upiprdrqimcejtdxaqrh&password=${SUPABASE_DB_PASSWORD}&prepareThreshold=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
